lidofinance/easy-track-ui

- modules/motions/hooks/usePeriodLimitsInfo.ts
- modules/motions/ui/MotionLimitProgress/MotionLimitProgress.tsx
Fix of the problem of incorrect calculation of the amount spent during the motion period
Check motion period limit statistic (period duration, period spent amount)
> fix: fix calc current period spent amount, update calc period start

- modules/blockChain/hooks/useTransactionSender.ts
- modules/motions/ui/MotionFormStartNew/MotionFormStartNew.tsx
- modules/shared/utils/getErrorMessage.ts
Fix error message after cancel tx
Took `getErrorMessage` from staking-widget-ts as sample
Try to create a motion, but do not confirm transaction in the wallet, cancel it instead.
> fix: error message after cancel tx

- modules/motions/providers/motionDetailed.tsx
- modules/motions/ui/MotionDetailed/MotionCardDetailed.tsx
- modules/motions/ui/MotionDetailed/MotionDetailedActions/MotionDetailedActions.tsx
- pages/motions/[motionId].tsx
Fixing error when motion page was losing enact/objection transaction state
> fix: object/enact transaction state moved to motion detailed provider

- modules/motions/ui/MotionFormStartNew/Parts/StartNewAllowedRecipientTopUp.tsx
- modules/motions/ui/MotionFormStartNew/Parts/StartNewNodeOperators.tsx
- modules/motions/ui/MotionFormStartNew/Parts/StartNewTopUpWithLimits.tsx
- modules/motions/ui/MotionLimitProgress/MotionLimitProgress.tsx
- modules/shared/ui/Controls/InputNumber/InputNumber.tsx
- modules/shared/ui/Controls/InputNumber/index.ts
Fixing a problem was occurring when top-up amount is not integer and top-up limit scale was not filled.
Also number-filtered input was added, reference: https://github.com/lidofinance/ethereum-staking-widget/blob/develop/shared/forms/components/input-number/input-number.tsx
> Top up limit scale for floats

- modules/motions/providers/motionDetailed.tsx
frame.sh wallet break support of eth_getLogs method
Wallet: frame.sh
Browser: firefox
> fix: get call data from rpc for motion enactment

- modules/wallet/ui/ConnectWalletModal/ConnectWalletModal.tsx
Hide wallets that appear after SDK update.
> fix: hide new wallets

- pages/api/node-operators/keys-info.ts
Move to new operators api. 
https://linear.app/lidofi/issue/VAL-448/deploy-node-operators-widget-ui-widget-backend
https://linear.app/lidofi/issue/DAO-188/migrate-et-ui-to-new-public-operators-api-at-mainnet
Code works at holesky from start
Operator names and key counts should be correct in motion and creation
> feat: update operator public API

- modules/blockChain/contractAddresses.ts
- modules/blockChain/contracts.ts
- modules/motions/evmAddresses.ts
- modules/motions/hooks/useAllowedTokensRegistry.ts
- modules/motions/hooks/useContractEvmScript.ts
- modules/motions/hooks/useRegistryWithLimits.ts
- modules/motions/types.ts
- modules/motions/ui/MotionDescription/MotionDescription.tsx
- modules/motions/ui/MotionFormStartNew/Parts/StartNewAllowedRecipientAdd.tsx
- modules/motions/ui/MotionFormStartNew/Parts/StartNewAllowedRecipientRemove.tsx
- modules/motions/ui/MotionFormStartNew/Parts/StartNewTopUpWithLimitsAndCustomToken.tsx
- modules/motions/ui/MotionFormStartNew/Parts/index.ts
- modules/motions/utils/getMotionTypeDisplayName.ts
Add missing top-up motions on Holesky Testnet according to the recent [docs](https://docs.lido.fi/deployed-contracts/holesky#easy-track-factories-for-token-transfers) update.
> feat: Holesky top up motions

- modules/blockChain/contractAddresses.ts
Correct EVMExecuter address at mainnet.
was:
now:
Motions with limits at mainnet only. Could be test at staging env
> fix: fix executer address at mainnet

- modules/blockChain/contractAddresses.ts
- modules/motions/evmAddresses.ts
- modules/motions/hooks/useTransitionLimits.ts
- Added new top-up stables factories for RCC, PML, and ATC. Addresses to check are available via [the docs](https://docs.lido.fi/deployed-contracts/holesky/#easy-track-factories-for-token-transfers);
- Transition limits updated according to the upcoming [voting script](https://github.com/lidofinance/scripts/blob/bda3568d1291bdc7ba422fb20150313f2d1778c3/scripts/vote_2024_01_16.py#L106)
> feat: rcc/pml/atc top up factories

- modules/motions/network/motionsSubgraphFetchers.ts
This PR adds the ability to fetch any motion by its id from the Subgraph without requirements on status.
> feat: fetch active motions from subgraph by id

- modules/blockChain/contractAddresses.ts
- modules/blockChain/contracts.ts
- modules/motions/evmAddresses.ts
- modules/motions/hooks/useAllowedTokensRegistry.ts
- modules/motions/hooks/useContractEvmScript.ts
- modules/motions/hooks/useEVMScriptDecoder.ts
- modules/motions/hooks/usePeriodLimitsInfo.ts
- modules/motions/hooks/useRegistryWithLimits.ts
- modules/motions/hooks/useTokenByTopUpType.ts
- modules/motions/hooks/useTransitionLimits.ts
- modules/motions/types.ts
- modules/motions/ui/MotionDescription/MotionDescription.tsx
- modules/motions/ui/MotionFormStartNew/Parts/StartNewTopUpWithLimits.tsx
- modules/motions/ui/MotionFormStartNew/Parts/StartNewTopUpWithLimitsAndCustomToken.tsx
- modules/motions/ui/MotionFormStartNew/Parts/index.ts
- modules/motions/utils/getMotionTypeDisplayName.ts
According to the upcoming Jan 23 [Omnibus](https://www.notion.so/Checklist-omnibus-23-01-2024-171-be9acb321e194688bcbc9bfcb090f015) changelog, we need to add the support of new top up factories and remove factories that were proposed to be removed.
- Added stETH Top Up EVM script factories for RCC, PML and ATC on Mainnet and Holesky Testnet;
- Removed DAI Top Up EVM script factories for RCC, PML and ATC;
- Added Stables Top Up EVM script factories for RCC, PML and ATC on Mainnet and Holesky Testnet.
- Removed DAI Top Up EVM script factory for LEGO;
- Added Stables Top Up EVM script factory for LEGO on Mainnet and Holesky Testnet.
New addresses are already available in the [Docs](https://docs.lido.fi/deployed-contracts/)
**Do not merge until the next omnibus is enacted!**
> feat: new top up factories

- modules/motions/hooks/useEVMScriptDecoder.ts
Add missing ABIs to `useEVMScriptDecoder`
> fix: add missing abi to decoder

- modules/motions/ui/MotionFormStartNew/Parts/StartNewTopUpWithLimitsAndCustomToken.tsx
- modules/tokens/utils/validateToken.ts
When using an input to enter an asset amount with a `decimals` value other than 18, an error may occur that blocks form submission.
This PR allows you to validate values for assets with any `decimals` value.
> fix: add custom decimals value validation

- modules/motions/types.ts
- modules/motions/ui/MotionDescription/DescSDVTNodeOperatorNamesSet.tsx
- modules/motions/ui/MotionDescription/DescSDVTNodeOperatorRewardAddressesSet.tsx
- modules/motions/ui/MotionDescription/DescSDVTTargetValidatorLimitsUpdate.tsx
- modules/motions/ui/MotionDescription/DescSDVTVettedValidatorsLimitsSet.tsx
- modules/motions/ui/MotionDescription/MotionDescription.tsx
- modules/motions/ui/MotionDescription/types.ts
- modules/motions/utils/formatMotionDataOnchain.ts
- modules/motions/utils/formatMotionDataSubgraph.ts
Remove on-chain node operators data from archived motions' descriptions
> fix: Simple DVT archived motions descriptions

- modules/stonks/hooks/useOrderData.ts
- modules/stonks/types.ts
- modules/stonks/ui/StonksOrderCard/StonksOrderCard.tsx
- modules/stonks/ui/StonksOrderCard/StonksOrderCardStyle.tsx
- modules/stonks/ui/StonksOrderResolverForm/StonksOrderResolverForm.tsx
- modules/stonks/utils/fetchOffChainOrder.ts
- modules/stonks/utils/getOffChainOrderUrl.ts
[Linear issue](https://linear.app/lidofi/issue/DAO-300/stonks-follow-up)
> Stonks Improvements 

- abi/dvt/SDVTRegistryV2.abi.json
- abi/dvt/UpdateTargetValidatorLimitsV2.abi.json
- modules/blockChain/contracts.ts
- modules/motions/evmAddresses.ts
- modules/motions/hooks/useContractEvmScript.ts
- modules/motions/hooks/useSDVTNodeOperatorsList.ts
- modules/motions/types.ts
- modules/motions/ui/MotionDescription/DescSDVTTargetValidatorLimitsUpdateV2.tsx
- modules/motions/ui/MotionDescription/MotionDescription.tsx
- modules/motions/ui/MotionFormStartNew/Parts/StartNewSDVTTargetValidatorLimitsUpdateV2.tsx
- modules/motions/ui/MotionFormStartNew/Parts/index.ts
- modules/motions/utils/getMotionTypeDisplayName.ts
This is a temporary solution related to #268. Since new versions of `UpdateTargetValidatorLimits` and SDVT registry contracts aren't deployed on the Mainnet, any update on production will break this and probably other Simple DVT motions functionality. Until then, we should divide these contracts into two versions since they have different ABIs on Mainnet and Holesky.
Merge this before any change in the production.
> fix: add temp fix for Update target validator limits sdvt motion

- modules/blockChain/contractAddresses.ts
- modules/blockChain/contracts.ts
- modules/motions/evmAddresses.ts
- modules/motions/hooks/useAvailableMotions.ts
- modules/motions/hooks/useContractEvmScript.ts
- modules/motions/hooks/useEVMScriptDecoder.ts
- modules/motions/hooks/useRegistryWithLimits.ts
- modules/motions/hooks/useTokenByTopUpType.ts
- modules/motions/types.ts
- modules/motions/ui/MotionDescription/MotionDescription.tsx
- modules/motions/ui/MotionFormStartNew/Parts/StartNewTopUpWithLimits.tsx
- modules/motions/ui/MotionFormStartNew/Parts/StartNewTopUpWithLimitsAndCustomToken.tsx
- modules/motions/ui/MotionFormStartNew/Parts/index.ts
- modules/motions/utils/getMotionType.ts
- modules/motions/utils/getMotionTypeDisplayName.ts
Holesky addresses reference: [docs](https://docs.lido.fi/deployed-contracts/holesky#easy-track-factories-for-token-transfers)
> feat: add top up factories for Ecosystem Ops and Labs Ops (stETH and stables)

- modules/network/utils/fetchWithFallback.ts
- pages/api/rpc.ts
Inprove fallback logic in case rpc api return 2xx (ok), but there is an error fields in response
Add more logs for grafana
> feat: add smart fallback it works on 200 with errors in batch requests

- next.config.mjs
When trying to add Hoodi-deployed application to the Safe applications on the dashboard it fails with the CORS error. For it to work well with the Safe, we need to update the CORS configs for that specific file not to expose other resources and set the allowed frame-ancestors to allow [app.safe.global](https://app.safe.global/welcome) and [app.safe.protofire.io](https://app.safe.protofire.io/welcome/accounts) to embed the app.
> Fix: add manifest.json CORS config for Safe App integration
