lidofinance/easy-track-ui

modules/shared/metrics/contractInfo.ts
This PR includes a change in how contract addresses are exported as prom metrics. Now addresses are exported together with a corresponding chain id.
=> feat(metrics): export contract addresses by chain

Dockerfile
Upgrade git version in dockerfile
=> fix: upgrade git version in docker file

.github/workflows/checks.yml, .github/workflows/ci-dev.yml, .github/workflows/ci-preview-deploy.yml, .github/workflows/ci-prod.yml, .github/workflows/ci-staging.yml, .github/workflows/create-tag-and-trigger-deploy.yml, .github/workflows/prepare-release.yml
=> Add actions linter

modules/motions/network/motionsSubgraphFetchers.ts, modules/shared/ui/Common/WarningBox/WarningBox.ts, modules/shared/ui/Common/WarningBox/index.ts, pages/archive.tsx
=> Subgraph error handler

.husky/commit-msg, .husky/pre-commit, commitlint.config.js, package.json, yarn.lock
Use commitlint for EasyTrack UI
=> Add commit linter

modules/motions/hooks/usePeriodLimitsInfo.ts, modules/motions/hooks/utils.test.ts, modules/motions/hooks/utils.ts, package.json, yarn.lock
Added tests. Fix case when motion creates in the current period and ends in the next period
=> feat: add tests for calc period limit

modules/shared/ui/Layout/Header/Header.tsx, modules/shared/ui/Layout/Header/HeaderStyle.ts, modules/shared/utils/csp.ts, package.json
=> WCv2 warning header overflow

modules/blockChain/contractAddresses.ts, modules/blockChain/contracts.ts, modules/motions/evmAddresses.ts, modules/motions/hooks/useContractEvmScript.ts, modules/motions/hooks/useEVMScriptDecoder.ts, modules/motions/hooks/useRegistryWithLimits.ts, modules/motions/types.ts, modules/motions/ui/MotionDescription/MotionDescription.tsx, modules/motions/ui/MotionFormStartNew/Parts/StartNewAllowedRecipientAdd.tsx, modules/motions/ui/MotionFormStartNew/Parts/StartNewAllowedRecipientRemove.tsx, modules/motions/ui/MotionFormStartNew/Parts/StartNewAllowedRecipientTopUp.tsx, modules/motions/ui/MotionFormStartNew/Parts/index.ts, modules/motions/utils/getMotionTypeDisplayName.ts
Rewards Share Program
**Goerli**
- AllowedRecipientsRegistry: `0x8b59609f4bEa230E565Ae0C3C7b6913746Df1cF2`
- AddAllowedRecipient: `0x51916FC3D24CbE19c5e981ae8650668A1F5cF19B`
- RemoveAllowedRecipient: `0x932aab3D6057ed2Beef95471414831C4535600E9`
- TopUpAllowedRecipients: `0x5Bb391170899A7b8455A442cca65078ff3E1639C`
- deployment_tx_hash: `0xab27a529345655af1b6ce5bb923259a357d87fff0ee94fcf244a5885d7ecb6d1`
**Mainnet**
- AllowedRecipientsRegistry: `0xdc7300622948a7AdaF339783F6991F9cdDD79776`
- AddAllowedRecipient: `0x1F809D2cb72a5Ab13778811742050eDa876129b6`
- RemoveAllowedRecipient: `0xd30Dc38EdEfc21875257e8A3123503075226E14B`
- TopUpAllowedRecipients: `0xbD08f9D6BF1D25Cc7407E4855dF1d46C2043B3Ea`
- deployment_tx_hash: `0x71527ca532b0664ad504c59b15fa5b0167788839cd59bd0aa8ba492afbedab41` …
=> Rewards share program motion types

.env.sample, README.md, next.config.mjs, pages/api/rpc.ts
=> feat: rpc urls env format changed

.github/workflows/ci-preview-deploy.yml
=> fix: preview stand for staging

LICENSE, package.json
=> feat: add gpl3 license

modules/motions/ui/MotionDescription/DescSDVTNodeOperatorNamesSet.tsx, modules/motions/ui/MotionDescription/DescSDVTNodeOperatorsActivate.tsx, modules/motions/ui/MotionDescription/DescSDVTNodeOperatorsDeactivate.tsx, modules/motions/ui/MotionDescription/DescSDVTTargetValidatorLimitsUpdate.tsx, modules/motions/ui/MotionDescription/DescSDVTVettedValidatorsLimitsSet.tsx, modules/motions/ui/MotionFormStartNew/Parts/StartNewSDVTNodeOperatorManagersChange.tsx, modules/motions/ui/MotionFormStartNew/Parts/StartNewSDVTNodeOperatorNamesSet.tsx, modules/motions/ui/MotionFormStartNew/Parts/StartNewSDVTNodeOperatorRewardAddressesSet.tsx, modules/motions/ui/MotionFormStartNew/Parts/StartNewSDVTNodeOperatorsActivate.tsx, modules/motions/ui/MotionFormStartNew/Parts/StartNewSDVTNodeOperatorsDeactivate.tsx, modules/motions/ui/MotionFormStartNew/Parts/StartNewSDVTTargetValidatorLimitsUpdate.tsx, modules/motions/ui/MotionFormStartNew/Parts/StartNewSDVTVettedValidatorsLimitsSet.tsx, modules/motions/ui/MotionFormStartNew/Parts/StartSDVTNodeOperatorsAdd.tsx
- Update new motions' descriptions;
- Update new forms' validation functions;
- Improve AddNodeOperators validation.
=> Refactor: more SDVT polishing

modules/blockChain/contractAddresses.ts, modules/motions/evmAddresses.ts, modules/motions/hooks/useAvailableMotions.ts, pages/api/node-operators/keys-info.ts
- New addresses added;
- Improve contract list filtration in `useAvailableMotions`;
- Remove redundant `console.log` calls.
=> Add SDVT contracts addresses on Holesky

.github/CODEOWNERS
=> feat: change code owners

modules/blockChain/utils/getGnosisSafeLink.ts, modules/motions/ui/MotionCardPreview/MotionCardPreviewStyle.ts, modules/motions/utils/getMotionProgress.ts
- Fixed Safe app link on Holesky
- Improved motion preview cards look
- Fixed objections value for motions on Holesky
[Linear link](https://linear.app/lidofi/issue/DAO-169/et-ui-sdvtholesky-feedback)
=> Holesky improvements and fixes

modules/motions/ui/MotionFormStartNew/Parts/StartNewSDVTNodeOperatorManagersChange.tsx, modules/motions/ui/MotionFormStartNew/Parts/StartNewSDVTNodeOperatorNamesSet.tsx, modules/motions/ui/MotionFormStartNew/Parts/StartNewSDVTNodeOperatorRewardAddressesSet.tsx, modules/motions/ui/MotionFormStartNew/Parts/StartNewSDVTNodeOperatorsActivate.tsx, modules/motions/ui/MotionFormStartNew/Parts/StartNewSDVTNodeOperatorsDeactivate.tsx, modules/motions/ui/MotionFormStartNew/Parts/StartNewSDVTTargetValidatorLimitsUpdate.tsx, modules/motions/ui/MotionFormStartNew/Parts/StartNewSDVTVettedValidatorsLimitsSet.tsx, modules/motions/ui/MotionFormStartNew/Parts/StartSDVTNodeOperatorsAdd.tsx, modules/motions/utils/getMotionTypeDisplayName.ts
=> Remove isValid condition for adding new program into motion

modules/motions/hooks/useTransitionLimits.ts, modules/motions/ui/MotionFormStartNew/Parts/StartNewTopUpWithLimitsAndCustomToken.tsx
This PR brings transition limits for newly supported tokens as well as improved transition limits calculation logic. It also brings a minor UX improvement to top up with token form validation.
=> New top up with token factories improvements

modules/motions/hooks/useNodeOperatorsList.ts, modules/network/hooks/useSwr.ts
[Link to the task](https://linear.app/lidofi/issue/DAO-177/et-ui-reload-motion-creation-without-reason)
=> [DAO-177] Fix "Start Motion page reloads without a reason" bug

modules/motions/types.ts, modules/motions/ui/MotionFormStartNew/Parts/StartNewTopUpWithLimits.tsx, modules/motions/ui/MotionFormStartNew/Parts/index.ts
Merge **only** if there is a need to merge #224 before next Aragon voting with RCC/ATC/PML stables top-up factories support.
=> feat: enable RCC/ATC/PML DAI top-up motions

modules/motions/hooks/useEVMScriptDecoder.ts
=> fix: add NOR abi to decoder hook

modules/blockChain/contractAddresses.ts, modules/motions/hooks/useAvailableMotions.ts, modules/motions/hooks/useTransitionLimits.ts, modules/motions/ui/MotionDescription/DescNodeOperatorLimitIncrease.tsx, modules/motions/ui/MotionFormStartNew/MotionFormStartNew.tsx
- Refactor available motions fetch logic;
- Fix Finance contract address on Holesky Testnet.
=> fix: available motions fetch logic

modules/blockChain/contractAddresses.ts, modules/motions/evmAddresses.ts
[Linear task](https://linear.app/lidofi/issue/DAO-212/%5Bet-ui%5D-add-simple-dvt-mainnet-support)
[Simple DVT addresses reference](https://docs.lido.fi/deployed-contracts/#easy-track-factories-for-staking-modules)
=> feat: Simple DVT Mainnet addresses

modules/motions/evmAddresses.ts
Mainnet contract deploy commit: https://github.com/lidofinance/easy-track/pull/71/commits/9039f23913ab263b530a58047848a4a1200f7f74
=> feat: add `CSMSettleElStealingPenalty` address on Mainnet

modules/motions/hooks/utils.test.ts, modules/motions/hooks/utils.ts
Fix limit period calculation
Should be correct, was wrong period (screenshot from Aug):
=> fix: fix calc period limits for middle months

.env.sample, modules/appWagmiConfig/appWagmiConfig.tsx, modules/blockChain/chains.ts, modules/blockChain/contractAddresses.ts, modules/blockChain/utils/getBackendRpcUrl.ts, modules/blockChain/utils/getGnosisSafeLink.ts, modules/motions/evmAddresses.ts, modules/shared/utils/sanitize.ts, next.config.mjs, package.json, pages/api/node-operators/keys-info.ts, pages/api/rpc.ts, pages/api/subgraph.ts, yarn.lock
Adds support for the Hoodi testnet.
=> DAO-609 Configure DAO EasyTrack UI for Hoodi testnet

pages/api/rpc.ts
fix error handle, in case it is real error from all providers
=> fix: return error, if get error at all fallbacks

modules/blockChain/contractAddresses.ts, modules/motions/evmAddresses.ts
=> [Hoodi] chore: add SDVT addresses 

middleware.ts
=> chore: add cache headers to the settings page

modules/blockChain/utils/createContractHelpers.ts, modules/motions/hooks/useAvailableMotions.ts, modules/motions/hooks/useNodeOperatorsList.ts, modules/motions/ui/MotionFormStartNew/Parts/StartNewSDVTTargetValidatorLimitsUpdateV2.tsx, modules/shared/utils/csp.ts
=> fix: update request splitting logic to better fit the api/rpc limits

modules/blockChain/contractAddresses.ts, modules/motions/evmAddresses.ts, modules/motions/hooks/useEVMScriptDecoder.ts, pages/api/rpc.ts
=> chore: add sandbox factories

modules/blockChain/constants.ts, modules/motions/hooks/useSDVTNodeOperatorsList.ts, modules/motions/utils/getManagerAddressesMap.ts, pages/api/rpc.ts
=> chore: get manager rate limit fix for sdtv

modules/blockChain/utils/createContractHelpers.ts, modules/blockChain/utils/getBatchProviderCacheSeed.ts, modules/motions/hooks/useAllowedTokensRegistry.ts, modules/motions/hooks/useAvailableMotions.ts, modules/motions/hooks/useNodeOperatorsList.ts, modules/motions/hooks/usePeriodLimitsInfo.ts, modules/motions/hooks/useSDVTNodeOperatorsList.ts, modules/motions/hooks/useSDVTNodeOperatorsSummary.ts, modules/motions/hooks/useTransitionLimits.ts, modules/motions/ui/MotionFormStartNew/Parts/StartNewSDVTNodeOperatorManagersChange.tsx, modules/motions/ui/MotionFormStartNew/Parts/StartNewSDVTNodeOperatorsActivate.tsx, modules/motions/ui/MotionFormStartNew/Parts/StartNewSDVTNodeOperatorsDeactivate.tsx, modules/motions/ui/MotionFormStartNew/Parts/StartNewSDVTTargetValidatorLimitsUpdateV2.tsx, modules/motions/utils/getMotionTypeDisplayName.ts, pages/api/rpc.ts
=> chore: update batching; fix motion creation form

modules/blockChain/utils/limitedJsonRpcBatchProvider.ts
=> fix: set chunk size to max provider batch

modules/blockChain/utils/limitedJsonRpcBatchProvider.ts, pages/api/rpc.ts
=> Quickfix: stonks page 

modules/blockChain/utils/limitedJsonRpcBatchProvider.ts, pages/api/rpc.ts
=> Develop -> Main

modules/blockChain/contractAddresses.ts, modules/blockChain/utils/formatBalanceIntl.ts, modules/dualGovernance/DualGovernanceWidget/DualGovernanceWidget.tsx, modules/shared/ui/Layout/Header/Header.tsx
- remove isTestnet flag for DG Widget
=> Develop => Main
